# Generated by Django 4.2.27 on 2026-05-20 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inhabitants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='households',
            name='Q51',
            field=models.IntegerField(blank=True, choices=[('yes', 'YES'), ('no', 'NO')], null=True),
        ),
        migrations.AlterField(
            model_name='households',
            name='Q52',
            field=models.IntegerField(blank=True, choices=[('1', 'Single House'), ('2', 'Duplex'), ('3', 'Multi-unit residential (tree units or more)'), ('4', 'Commercial/industrial/agricultural'), ('5', 'Insitutional Living Quarter (hotel, hjospital)'), ('6', 'Other housing units (boat,cave,others)')], null=True),
        ),
        migrations.AlterField(
            model_name='households',
            name='Q53',
            field=models.IntegerField(blank=True, choices=[('0', 'No Walls'), ('1', 'Makeshift/salvaged/improvised materials'), ('2', 'Glass'), ('3', 'Asbestos'), ('4', 'Bamboo/Sawali/Cogon/Nipa'), ('5', 'Galvanized Iron/Aluminum'), ('6', 'Half Concreate/brick/stone and half wood'), ('7', 'Wood'), ('8', 'Concrete/brick/stone'), ('9', 'Others')], null=True),
        ),
    ]
