# Generated by Django 4.2.27 on 2026-05-20 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inhabitants', '0003_alter_households_q45_alter_households_q46_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='households',
            name='Q50B',
        ),
        migrations.AlterField(
            model_name='households',
            name='Q51',
            field=models.IntegerField(blank=True, choices=[('0', '0 None'), ('1', '1 Open pit'), ('2', '2 Close pit'), ('3', '3 Water-sealed, other depository, shared'), ('4', '4 Water-sealed, other depository, exclusive'), ('5', '5 Water-sealed, sewer septictank, shared'), ('6', '6 Water-sealed, sewer septic tank, exclusive'), ('7', '7 Others')], null=True),
        ),
        migrations.AlterField(
            model_name='inhabitants',
            name='q25a',
            field=models.CharField(blank=True, choices=[('yes', '1 YES'), ('no', '1 NO')], default='no', max_length=3, null=True),
        ),
    ]
