# Generated by Django 4.2.27 on 2026-05-25 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inhabitants', '0003_alter_households_q45_alter_households_q46_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inhabitants',
            name='contactno',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='inhabitants',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='inhabitants',
            name='leftthumb',
            field=models.ImageField(blank=True, upload_to='thumb/'),
        ),
        migrations.AddField(
            model_name='inhabitants',
            name='occupation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='inhabitants',
            name='philsysno',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='inhabitants',
            name='photo',
            field=models.ImageField(blank=True, upload_to='rbi/'),
        ),
        migrations.AddField(
            model_name='inhabitants',
            name='rbisector',
            field=models.CharField(blank=True, choices=[('LABOR/EMPLOYED', 'LABOR/EMPLOYED'), ('UNEMPLOYED', 'UNEMPLOYED'), ('PWD', 'PWD'), ('OFW', 'OFW'), ('SOLOPARENT', 'SOLOPARENT'), ('OSY', 'OSY'), ('OSC', 'OSC'), ('IP', 'IP')], max_length=200),
        ),
        migrations.AddField(
            model_name='inhabitants',
            name='rightthumb',
            field=models.ImageField(blank=True, upload_to='thumb/'),
        ),
        migrations.AlterField(
            model_name='households',
            name='Q51',
            field=models.IntegerField(blank=True, choices=[('0', '0 None'), ('1', '1 Open pit'), ('2', '2 Close pit'), ('3', '3 Water-sealed, other depository, shared'), ('4', '4 Water-sealed, other depository, exclusive'), ('5', '5 Water-sealed, sewer septictank, shared'), ('6', '6 Water-sealed, sewer septic tank, exclusive'), ('7', '7 Others')], null=True),
        ),
        migrations.AlterField(
            model_name='inhabitants',
            name='q25a',
            field=models.CharField(blank=True, choices=[('yes', '1 YES'), ('no', '1 NO')], default='no', max_length=3, null=True),
        ),
    ]
