# Generated by Django 4.2.27 on 2026-05-20 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inhabitants', '0004_remove_households_q50b_alter_households_q51_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='households',
            name='Q50B',
            field=models.IntegerField(blank=True, choices=[('yes', '1 YES'), ('no', '2 NO')], null=True),
        ),
    ]
