# Generated by Django 4.2.27 on 2026-06-23 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inhabitants', '0004_inhabitants_contactno_inhabitants_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inhabitants',
            name='q25a',
            field=models.CharField(blank=True, choices=[('yes', '1 YES'), ('no', '2 NO')], default='no', max_length=3, null=True),
        ),
    ]
