# Generated by Django 4.2.27 on 2026-05-22 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inhabitants', '0005_households_q50b'),
    ]

    operations = [
        migrations.AddField(
            model_name='inhabitants',
            name='contactno',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='inhabitants',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='inhabitants',
            name='philsysno',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='inhabitants',
            name='photo',
            field=models.ImageField(blank=True, upload_to='media/rbi/'),
        ),
        migrations.AddField(
            model_name='inhabitants',
            name='rbisector',
            field=models.CharField(blank=True, choices=[('1', 'LABOR/EMPLOYED'), ('2', 'UNEMPLOYED'), ('3', 'PWD'), ('4', 'OFW'), ('5', 'SOLOPARENT'), ('6', 'OSY'), ('7', 'OSC'), ('8', 'IP')], max_length=200),
        ),
    ]
