# Generated by Django 4.2.27 on 2026-05-22 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inhabitants', '0006_inhabitants_contactno_inhabitants_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inhabitants',
            name='leftthumb',
            field=models.ImageField(blank=True, upload_to='media/thumb/'),
        ),
        migrations.AddField(
            model_name='inhabitants',
            name='rightthumb',
            field=models.ImageField(blank=True, upload_to='media/thumb/'),
        ),
    ]
