# Generated by Django 4.2.27 on 2026-05-22 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inhabitants', '0007_inhabitants_leftthumb_inhabitants_rightthumb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inhabitants',
            name='leftthumb',
            field=models.ImageField(blank=True, upload_to='thumb/'),
        ),
        migrations.AlterField(
            model_name='inhabitants',
            name='photo',
            field=models.ImageField(blank=True, upload_to='rbi/'),
        ),
        migrations.AlterField(
            model_name='inhabitants',
            name='rightthumb',
            field=models.ImageField(blank=True, upload_to='thumb/'),
        ),
    ]
