# Generated by Django 4.2.27 on 2026-05-22 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inhabitants', '0008_alter_inhabitants_leftthumb_alter_inhabitants_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inhabitants',
            name='occupation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
