# Generated by Django 4.2.27 on 2026-05-23 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inhabitants', '0009_inhabitants_occupation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inhabitants',
            name='rbisector',
            field=models.CharField(blank=True, choices=[('LABOR/EMPLOYED', 'LABOR/EMPLOYED'), ('UNEMPLOYED', 'UNEMPLOYED'), ('PWD', 'PWD'), ('OFW', 'OFW'), ('SOLOPARENT', 'SOLOPARENT'), ('OSY', 'OSY'), ('OSC', 'OSC'), ('IP', 'IP')], max_length=200),
        ),
    ]
