# Generated by Django 4.2.27 on 2026-05-19 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='barangay',
            name='logo',
            field=models.FileField(default='', upload_to='media/logo/'),
            preserve_default=False,
        ),
    ]
