# Generated by Django 4.2.27 on 2026-05-19 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbi', '0002_barangay_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='religion',
            name='description',
            field=models.CharField(max_length=500),
        ),
    ]
