# Generated by Django 4.2.27 on 2026-05-19 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbi', '0003_alter_religion_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barangay',
            name='logo',
            field=models.FileField(upload_to='logo/'),
        ),
    ]
